import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sun, 
  Wind, 
  Layers, 
  Zap, 
  Shield, 
  Flame, 
  Gauge, 
  Home, 
  Compass, 
  CheckCircle2, 
  HelpCircle,
  TrendingUp,
  Settings,
  Tv
} from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

type SectionId = 'producers' | 'national' | 'local' | 'neighborhood' | 'acm';

interface GridSectionInfo {
  title: string;
  subtitle: string;
  description: string;
  highlights: string[];
}

export default function GridChainVisualization() {
  const { t } = useLanguage();
  const [activeSection, setActiveSection] = useState<SectionId>('local');
  const [hoveredSection, setHoveredSection] = useState<SectionId | null>(null);

  // Translation mapping for bilingual support
  const sectionData: Record<SectionId, { nl: GridSectionInfo; en: GridSectionInfo }> = {
    producers: {
      nl: {
        title: 'Energieproducenten',
        subtitle: 'Centrale & Decentrale Opwekking',
        description: 'De bron van het energiesysteem. Hier wordt elektriciteit opgewekt door diverse producenten. In de nieuwe visie verschuift de nadruk van centrale fossiele centrales naar grootschalige windparken en zonne-installaties.',
        highlights: [
          'Grootschalige windturbines op zee en land',
          'Zonneparken en industriële opwekking',
          'Voorkeur voor directe gelijkstroom (DC) integratie waar mogelijk'
        ]
      },
      en: {
        title: 'Energy Producers',
        subtitle: 'Centralized & Decentralized Generation',
        description: 'The foundation of the energy system. This is where electricity is generated by various producers. In our new vision, the focus shifts from centralized fossil plants to large-scale wind farms and solar installations.',
        highlights: [
          'Large-scale offshore and onshore wind turbines',
          'Solar parks and industrial-scale generation',
          'Preference for direct DC integration where possible'
        ]
      }
    },
    national: {
      nl: {
        title: 'Nationaal / Regionaal Net',
        subtitle: 'Transport over Grote Afstanden',
        description: 'De transport-snelweg van ons land. Beheerd door partijen zoals TenneT (hoogspanning) en regionale netbeheerders zoals Stedin en Liander. Ook gas- en waterstoftransport (Gasunie, Hynetwerk) maakt hier deel van uit.',
        highlights: [
          'Elektriciteitstransport via HS/MS/LS-lijnen (TenneT, Stedin, Liander)',
          'Gastransport en toekomstige waterstof-backbones (Gasunie, Hynetwerk)',
          'Hoge gevoeligheid voor congestie door toenemende decentralisatie'
        ]
      },
      en: {
        title: 'National & Regional Grid',
        subtitle: 'Long-Distance Transmission',
        description: 'The transport highway of the nation. Managed by transmission system operators like TenneT (high voltage) and regional grid operators like Stedin and Liander. Also encompasses gas and hydrogen transport (Gasunie, Hynetwerk).',
        highlights: [
          'Electricity transport via HV/MV/LV lines (TenneT, Stedin, Liander)',
          'Gas transport and future hydrogen backbones (Gasunie, Hynetwerk)',
          'Highly sensitive to grid congestion due to rapid decentralization'
        ]
      }
    },
    local: {
      nl: {
        title: 'Lokaal Net (Decentraal)',
        subtitle: 'Het Intelligente Micro-Grid',
        description: 'Een zelfvoorzienend lokaal distributiesysteem (GDS) dat fungeert als slim micro-grid. Door lokaal te balanceren wordt de belasting op het nationale net geminimaliseerd.',
        highlights: [
          'Slimme distributiesystemen met actieve monitoring',
          'Betrouwbare AC fall-back back-up integratie',
          'Voorkomt lokale netcongestie en maakt snelle gebiedsontwikkeling mogelijk'
        ]
      },
      en: {
        title: 'Local Grid (Decentralized)',
        subtitle: 'The Intelligent Microgrid',
        description: 'An autonomous local distribution system (GDS) functioning as a smart microgrid. By balancing energy locally, stress on the national grid is minimized.',
        highlights: [
          'Smart distribution systems with real-time monitoring',
          'Highly reliable AC fall-back backup integration',
          'Eliminates local grid congestion and accelerates land development'
        ]
      }
    },
    neighborhood: {
      nl: {
        title: 'Buurtbalans',
        subtitle: 'Huishoudens & Bedrijven',
        description: 'De eindverbruikers die ook zelf opwekken en opslaan. Binnen de buurt worden afname en opwekking direct op elkaar afgestemd om transportverliezen te elimineren.',
        highlights: [
          'Lokale zonnepanelen (afname & opwek balans)',
          'Buurtbatterijen en geoptimaliseerde EV-laadstations',
          'Actieve energiegemeenschap die energie onderling deelt'
        ]
      },
      en: {
        title: 'Neighborhood Balance',
        subtitle: 'Households & Businesses',
        description: 'End-users who also generate and store energy. Within the neighborhood, local consumption and generation are directly balanced to eliminate distribution losses.',
        highlights: [
          'Rooftop solar panels (balancing supply & demand)',
          'Neighborhood batteries and smart EV charging stations',
          'Active energy community sharing power peer-to-peer'
        ]
      }
    },
    acm: {
      nl: {
        title: 'Toezichthouder ACM',
        subtitle: 'Autoriteit Consument & Markt',
        description: 'De onafhankelijke toezichthouder die toeziet op een eerlijke, transparante en betrouwbare energiemarkt. Zij bewaken de spelregels voor tarieven, netbeheer en consumentenrechten.',
        highlights: [
          'Reguleert energietarieven en voorwaarden',
          'Toezicht op onafhankelijkheid en prestaties netbeheerders',
          'Zorgt voor eerlijke concurrentie en consumentenbescherming'
        ]
      },
      en: {
        title: 'Regulator ACM',
        subtitle: 'Authority for Consumers & Markets',
        description: 'The independent regulator overseeing a fair, transparent, and reliable energy market. They safeguard the rules for tariffs, grid operators, and consumer protection.',
        highlights: [
          'Regulates energy tariffs, network codes, and conditions',
          'Monitors independence and performance of system operators',
          'Ensures fair competition and robust consumer rights protection'
        ]
      }
    }
  };

  const getTranslatedInfo = (id: SectionId) => {
    const lang = t('nl', 'en') === 'nl' ? 'nl' : 'en';
    return sectionData[id][lang];
  };

  const activeInfo = getTranslatedInfo(activeSection);

  return (
    <section id="grid-chain-visualization" className="py-24 bg-gradient-to-b from-slate-900 via-slate-950 to-indigo-950 text-white overflow-hidden border-t border-slate-800 relative">
      {/* Background glow effects */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="container mx-auto px-6 max-w-7xl">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <span className="inline-flex items-center gap-1.5 py-1 px-3 rounded-full bg-teal-550/10 text-teal-400 text-xs font-semibold uppercase tracking-wider mb-3">
              <Compass className="w-3.5 h-3.5" />
              {t('Systeem Keten', 'System Chain')}
            </span>
            <h2 className="text-3xl md:text-4xl font-extrabold tracking-tight mb-4 text-white">
              {t('Van Bron tot Buurtbalans', 'From Source to Neighborhood')}
            </h2>
            <p className="text-slate-400 text-base md:text-lg">
              {t(
                'De volledige energie-infrastructuur in kaart gebracht. Klik op de verschillende segmenten in ons interactieve diagram om te ontdekken hoe wij het netontwerp herdefiniëren.',
                'The complete energy infrastructure mapped out. Click on the different segments in our interactive diagram to discover how we redefine the grid design.'
              )}
            </p>
          </motion.div>
        </div>

        {/* Panoramic Schematic Diagram Area */}
        <div className="bg-slate-900/40 rounded-3xl border border-slate-800/80 p-6 md:p-8 mb-10 shadow-2xl relative overflow-hidden">
          
          {/* Subtle grid lines in sky layer */}
          <div className="absolute inset-x-0 top-0 h-44 bg-[linear-gradient(to_right,#334155_1px,transparent_1px)] bg-[size:3rem_3rem] opacity-20 pointer-events-none" />
          
          {/* Legend indicator */}
          <div className="absolute top-4 left-4 z-10 hidden sm:flex items-center gap-2 bg-slate-900/80 px-3 py-1.5 rounded-full border border-slate-800 text-[10px] font-mono tracking-wider text-slate-400">
            <span className="w-2.5 h-2.5 bg-teal-400 rounded-full animate-pulse" />
            <span>{t('INTERACTIEF SCHEMA - KLIK OP ONDERDELEN', 'INTERACTIVE SCHEMATIC - CLICK ON COMPONENTS')}</span>
          </div>

          {/* MAIN DIAGRAM CONTAINER (Responsive Flex/Grid on Mobile, Panoramic on Desktop) */}
          <div className="relative min-h-[480px] flex flex-col justify-between">
            
            {/* SKY LAYER: ACM Regulator Helicopter */}
            <div className="h-28 relative flex items-center justify-end pr-12 md:pr-24">
              <motion.button
                onClick={() => setActiveSection('acm')}
                onMouseEnter={() => setHoveredSection('acm')}
                onMouseLeave={() => setHoveredSection(null)}
                animate={{ 
                  y: [0, -6, 0],
                  x: [0, 4, 0]
                }}
                transition={{ 
                  repeat: Infinity, 
                  duration: 4, 
                  ease: "easeInOut" 
                }}
                className={`relative flex flex-col items-center p-3 rounded-2xl border transition-all duration-300 group z-10 ${
                  activeSection === 'acm' || hoveredSection === 'acm'
                    ? 'bg-amber-500/10 border-amber-400 text-amber-300 shadow-lg shadow-amber-500/10'
                    : 'bg-slate-950/40 border-slate-800 text-slate-400 hover:border-slate-700 hover:text-slate-200'
                }`}
              >
                {/* Helicopter Icon Container */}
                <div className="relative w-16 h-10 flex items-center justify-center">
                  {/* Rotor Blade (Animated spinning effect) */}
                  <div className="absolute top-0 left-1/2 -translate-x-1/2 w-12 h-1 bg-slate-400 rounded-full animate-[spin_0.15s_linear_infinite]" />
                  {/* Helicopter body */}
                  <div className="w-10 h-6 bg-current rounded-full relative mt-2 flex items-center justify-center">
                    <div className="absolute right-1 top-1 w-3 h-2 bg-slate-900/60 rounded-sm" /> {/* Windshield */}
                    <div className="absolute -left-4 top-1/2 -translate-y-1/2 w-5 h-1.5 bg-current rounded-full" /> {/* Tail */}
                    <div className="absolute -left-4 top-1/2 -translate-y-1.5 w-1 h-3 bg-current rounded-sm animate-[spin_0.3s_linear_infinite]" /> {/* Tail rotor */}
                  </div>
                  {/* Skids */}
                  <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-8 h-1 bg-current rounded-sm" />
                </div>
                <span className="text-[10px] font-bold tracking-wider mt-1.5 uppercase">ACM {t('Toezichthouder', 'Regulator')}</span>
                
                {/* Pulsing indicator */}
                <span className="absolute -top-1 -right-1 w-2.5 h-2.5 bg-amber-500 rounded-full animate-ping pointer-events-none" />
              </motion.button>
            </div>

            {/* GROUND & INFRASTRUCTURE LAYER (Panoramic 4 Columns) */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-6 items-end relative z-10">
              
              {/* Column 1: Energieproducenten */}
              <motion.div
                onClick={() => setActiveSection('producers')}
                onMouseEnter={() => setHoveredSection('producers')}
                onMouseLeave={() => setHoveredSection(null)}
                className={`cursor-pointer p-5 rounded-2xl border transition-all duration-300 flex flex-col items-center min-h-[170px] justify-between relative ${
                  activeSection === 'producers' || hoveredSection === 'producers'
                    ? 'bg-gradient-to-t from-slate-950 to-slate-900 border-teal-500 shadow-lg shadow-teal-500/5'
                    : 'bg-slate-950/20 border-slate-800/80 hover:border-slate-700'
                }`}
              >
                {/* Icons Area */}
                <div className="flex gap-4 items-end mb-4 h-16 text-slate-400">
                  {/* Wind turbine */}
                  <div className="relative w-10 h-16 flex items-end justify-center">
                    <div className="w-1 h-12 bg-slate-500 rounded-t" /> {/* Tower */}
                    {/* Spinning Blades */}
                    <div className="absolute top-1 w-10 h-10 animate-[spin_6s_linear_infinite] origin-center flex items-center justify-center">
                      <div className="w-1 h-10 bg-slate-300 absolute" />
                      <div className="w-10 h-1 bg-slate-300 absolute" style={{ transform: 'rotate(60deg)' }} />
                      <div className="w-10 h-1 bg-slate-300 absolute" style={{ transform: 'rotate(120deg)' }} />
                    </div>
                  </div>

                  {/* Solar Panel */}
                  <div className="relative w-10 h-10 border border-slate-600 bg-slate-850 rounded transform rotate-12 flex flex-col justify-between p-1">
                    <div className="grid grid-cols-3 gap-0.5 h-full">
                      <div className="bg-slate-700 rounded-sm" />
                      <div className="bg-slate-700 rounded-sm" />
                      <div className="bg-slate-700 rounded-sm" />
                      <div className="bg-slate-700 rounded-sm" />
                      <div className="bg-slate-700 rounded-sm" />
                      <div className="bg-slate-700 rounded-sm" />
                    </div>
                  </div>
                </div>

                <div className="text-center">
                  <span className="text-xs font-bold block mb-0.5 text-white">{t('Energieproducenten', 'Energy Producers')}</span>
                  <span className="text-[9px] font-mono text-slate-500 block uppercase">{t('Zon & Wind opwek', 'Solar & Wind Generation')}</span>
                </div>
              </motion.div>

              {/* Column 2: Nationaal / Regionaal net */}
              <motion.div
                onClick={() => setActiveSection('national')}
                onMouseEnter={() => setHoveredSection('national')}
                onMouseLeave={() => setHoveredSection(null)}
                className={`cursor-pointer p-5 rounded-2xl border transition-all duration-300 flex flex-col items-center min-h-[170px] justify-between relative ${
                  activeSection === 'national' || hoveredSection === 'national'
                    ? 'bg-gradient-to-t from-slate-950 to-slate-900 border-teal-500 shadow-lg shadow-teal-500/5'
                    : 'bg-slate-950/20 border-slate-800/80 hover:border-slate-700'
                }`}
              >
                {/* Icons Area: High voltage tower */}
                <div className="flex gap-4 items-end mb-4 h-16 text-slate-400">
                  {/* Transmission Pylon SVG */}
                  <svg className="w-12 h-16 text-slate-500" viewBox="0 0 40 60" fill="none">
                    <path d="M 20,4 L 10,60 M 20,4 L 30,60" stroke="currentColor" strokeWidth="1.5" />
                    <path d="M 5,20 L 35,20 M 2,35 L 38,35 M 10,50 L 30,50" stroke="currentColor" strokeWidth="1.5" />
                    <path d="M 5,20 L 20,35 M 35,20 L 20,35 M 10,35 L 20,50 M 30,35 L 20,50" stroke="currentColor" strokeWidth="1" />
                    <circle cx="20" cy="4" r="1.5" fill="currentColor" />
                  </svg>

                  {/* Gasunie pipeline symbol */}
                  <div className="flex flex-col items-center">
                    <div className="flex gap-1 items-end h-8">
                      <div className="w-1.5 h-5 bg-slate-600 rounded-t" />
                      <div className="w-6 h-2 bg-slate-600 border-t border-slate-500" />
                      <div className="w-1.5 h-5 bg-slate-600 rounded-t" />
                    </div>
                    <span className="text-[8px] font-mono text-slate-500">Gas / H2</span>
                  </div>
                </div>

                <div className="text-center">
                  <span className="text-xs font-bold block mb-0.5 text-white">{t('Nationaal / Regionaal net', 'National Grid')}</span>
                  <span className="text-[9px] font-mono text-slate-500 block uppercase">{t('TenneT, Stedin, Gasunie', 'TenneT, Stedin, Gasunie')}</span>
                </div>
              </motion.div>

              {/* Column 3: Lokaal net */}
              <motion.div
                onClick={() => setActiveSection('local')}
                onMouseEnter={() => setHoveredSection('local')}
                onMouseLeave={() => setHoveredSection(null)}
                className={`cursor-pointer p-5 rounded-2xl border transition-all duration-300 flex flex-col items-center min-h-[170px] justify-between relative ${
                  activeSection === 'local' || hoveredSection === 'local'
                    ? 'bg-gradient-to-t from-slate-950 to-slate-900 border-teal-500 shadow-lg shadow-teal-500/5 ring-1 ring-teal-500/20'
                    : 'bg-slate-950/20 border-slate-800/80 hover:border-slate-700'
                }`}
              >
                {/* Pulsing focal point */}
                <span className="absolute -top-1.5 -right-1.5 w-3 h-3 bg-teal-400 rounded-full animate-ping pointer-events-none" />
                
                {/* Icons Area: Smart Transformer Box / GDS Container */}
                <div className="flex gap-4 items-end mb-4 h-16 text-slate-400">
                  <div className="w-16 h-12 bg-slate-850 rounded-xl border border-slate-700 shadow-inner flex items-center justify-center relative p-2">
                    <Zap className="w-6 h-6 text-teal-400 animate-pulse" />
                    <div className="absolute top-1 right-1 flex gap-0.5">
                      <span className="w-1 h-1 bg-emerald-500 rounded-full animate-ping" />
                      <span className="w-1.5 h-1.5 bg-slate-600 rounded-full" />
                    </div>
                  </div>
                </div>

                <div className="text-center">
                  <span className="text-xs font-bold block mb-0.5 text-white">{t('Lokaal Net (Decentraal)', 'Local Grid')}</span>
                  <span className="text-[9px] font-mono text-teal-400 block uppercase font-semibold">{t('Smart Grid & Fall-back', 'Smart Grid & Fall-back')}</span>
                </div>
              </motion.div>

              {/* Column 4: Buurtbalans */}
              <motion.div
                onClick={() => setActiveSection('neighborhood')}
                onMouseEnter={() => setHoveredSection('neighborhood')}
                onMouseLeave={() => setHoveredSection(null)}
                className={`cursor-pointer p-5 rounded-2xl border transition-all duration-300 flex flex-col items-center min-h-[170px] justify-between relative ${
                  activeSection === 'neighborhood' || hoveredSection === 'neighborhood'
                    ? 'bg-gradient-to-t from-slate-950 to-slate-900 border-teal-500 shadow-lg shadow-teal-500/5'
                    : 'bg-slate-950/20 border-slate-800/80 hover:border-slate-700'
                }`}
              >
                {/* Icons Area: Home, EV charging, storage */}
                <div className="flex gap-4 items-end mb-4 h-16 text-slate-400">
                  {/* Smart Home */}
                  <div className="relative">
                    <Home className="w-8 h-8 text-emerald-400" />
                    <div className="absolute -top-1 left-1.5 w-5 h-1.5 bg-amber-500 rounded-sm" /> {/* Rooftop solar panel */}
                  </div>

                  {/* Smart greenhouse / neighborhood asset */}
                  <div className="w-10 h-7 border border-slate-650 bg-slate-900/40 rounded-t-lg flex flex-col justify-between p-0.5">
                    <div className="grid grid-cols-2 gap-0.5 h-full">
                      <div className="border border-slate-700 rounded-sm" />
                      <div className="border border-slate-700 rounded-sm" />
                    </div>
                  </div>
                </div>

                <div className="text-center">
                  <span className="text-xs font-bold block mb-0.5 text-white">{t('Buurtbalans', 'Neighborhood Balance')}</span>
                  <span className="text-[9px] font-mono text-slate-500 block uppercase">{t('Huishoudens & Opslag', 'Households & Storage')}</span>
                </div>
              </motion.div>

            </div>

            {/* UNDERGROUND LAYER: FLUORESCENT SYSTEM BUS PIPES */}
            <div className="h-16 relative mt-6 shrink-0 bg-slate-950 rounded-2xl border border-slate-800 flex items-center overflow-hidden">
              
              {/* Subtle brown/soil texture backing */}
              <div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-900 to-slate-950 opacity-50" />
              
              {/* SVG containing the Glowing pipelines mirroring the original diagram */}
              <svg className="absolute inset-0 w-full h-full" fill="none" preserveAspectRatio="none" viewBox="0 0 1000 64">
                
                {/* 1. Main local Direct Current (DC) bus - bright teal */}
                <path d="M 50,32 L 950,32" stroke="#14b8a6" strokeWidth="3" strokeDasharray="15 10" className="animate-[dash_20s_linear_infinite]" />
                
                {/* 2. AC Fallback Backup line - pulsing purple/indigo */}
                <path d="M 280,48 L 780,48" stroke="#a855f7" strokeWidth="2" strokeDasharray="8 12" className="animate-[dash_35s_linear_infinite]" />

                {/* 3. Gas / H2 pipe connecting producers/national net to regional system */}
                <path d="M 100,16 L 500,16" stroke="#4f46e5" strokeWidth="1.5" strokeDasharray="20 15" className="animate-[dash_40s_linear_infinite]" strokeOpacity="0.7" />

                {/* T-junction drops to soil (representing geothermal loop or connections) */}
                <path d="M 850,32 L 850,56" stroke="#14b8a6" strokeWidth="2" />
                <circle cx="850" cy="56" r="3" fill="#14b8a6" />

                {/* Grid Connection anchor drop */}
                <path d="M 380,32 L 380,48" stroke="#a855f7" strokeWidth="1.5" />
              </svg>

              {/* Responsive Legend indicators for pipes */}
              <div className="absolute left-6 text-[9px] font-mono text-teal-400 flex items-center gap-1.5 z-10 bg-slate-950/80 px-2 py-0.5 rounded border border-slate-800/60">
                <span className="w-2 h-2 bg-teal-400 rounded-full animate-pulse" />
                <span>{t('LOKAAL SMART-GRID (DC BUS)', 'LOCAL SMART-GRID (DC BUS)')}</span>
              </div>

              <div className="absolute right-6 text-[9px] font-mono text-purple-400 flex items-center gap-1.5 z-10 bg-slate-950/80 px-2 py-0.5 rounded border border-slate-800/60">
                <span className="w-2 h-2 bg-purple-500 rounded-full" />
                <span>{t('AC FALL-BACK STANDBY', 'AC FALL-BACK STANDBY')}</span>
              </div>
            </div>

          </div>

        </div>

        {/* Detailed Explanation Drawer below the diagram */}
        <div className="max-w-4xl mx-auto">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeSection}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -15 }}
              transition={{ duration: 0.3 }}
              className="bg-slate-900/80 backdrop-blur-md rounded-3xl p-8 border border-slate-800/90 shadow-2xl relative"
            >
              {/* Floating icon representing category */}
              <div className="absolute -top-5 left-8 p-3 bg-gradient-to-br from-teal-500 to-emerald-500 text-slate-950 rounded-2xl shadow-lg border border-teal-400">
                {activeSection === 'producers' && <Wind className="w-5 h-5" />}
                {activeSection === 'national' && <Layers className="w-5 h-5" />}
                {activeSection === 'local' && <Zap className="w-5 h-5" />}
                {activeSection === 'neighborhood' && <Home className="w-5 h-5" />}
                {activeSection === 'acm' && <Shield className="w-5 h-5" />}
              </div>

              <div className="pl-4 pt-2">
                <div className="flex flex-wrap items-center justify-between gap-4 mb-4">
                  <div>
                    <h3 className="text-2xl font-black text-white tracking-tight">
                      {activeInfo.title}
                    </h3>
                    <p className="text-teal-400 text-xs font-mono font-semibold uppercase tracking-wider mt-0.5">
                      {activeInfo.subtitle}
                    </p>
                  </div>

                  {/* Toezicht Helicopter Reference */}
                  {activeSection === 'acm' && (
                    <span className="text-[10px] bg-amber-500/10 border border-amber-500/30 text-amber-300 font-mono px-3 py-1 rounded-full">
                      {t('Zelfstandig Bestuursorgaan', 'Independent Regulator')}
                    </span>
                  )}
                </div>

                <p className="text-slate-300 text-sm md:text-base leading-relaxed mb-6">
                  {activeInfo.description}
                </p>

                {/* Grid of details */}
                <div className="grid sm:grid-cols-3 gap-4 border-t border-slate-800/60 pt-6">
                  {activeInfo.highlights.map((highlight, index) => (
                    <div key={index} className="flex gap-2.5 items-start">
                      <CheckCircle2 className="w-4.5 h-4.5 text-teal-400 mt-0.5 shrink-0" />
                      <span className="text-xs text-slate-350 leading-relaxed">{highlight}</span>
                    </div>
                  ))}
                </div>
              </div>

            </motion.div>
          </AnimatePresence>
        </div>

      </div>
      
      {/* Embedded style tag for animated grid lines */}
      <style>{`
        @keyframes dash {
          to {
            stroke-dashoffset: -1000;
          }
        }
      `}</style>
    </section>
  );
}
